### PR TITLE
Make read and write locks useful

### LINKED ISSUE #14: Usefulness of locks
Thank you for creating this awesome project. The only issue I have is that the current state of the read and write lock are lacking helper functions to be useful. I see the following main issues:

1) microkv uses bincode serialization, when only having the IndexMap (e.g., read or write lock) users would have to do the serialization + encryption themselves
2) making matters worse, external encryption part cannot rely on the stored secret as it is private. So users would need to store it in a second place
3) formatting the namespace strings is private, so users cannot access them and need to build them in the closure themselves (which is not very nice)

I propose we extend the index map in such a way that we have helper functions (that are also used internally by the namespaces). With them, users can use them inside a lock like this

```
db.lock_write(|mut kv| {
    kv.kv_put(db, "namespace", "key", 1);
}
```

I created a PR that serves as a proposal to discuss a a possible direction we could go to solve this problem (#15). If this is the way we want to go, I can extend it to the remaining useful functions and we can merge the PR.

I would love to hear your opinion on this issue.

### PR DESCRIPTION
**Pull request by plainerman**
This PR would close #14. It servers as a proposal to discuss the direction we should go to solve this problem. If this is the way we want to go, I can extend it to the remaining useful functions and we can merge the PR.

### CODE REVIEW

**Comment by ex0dus-0x** [comment]
Thanks for bringing up your concerns and starting the PR! Your suggestions make sense, as locked operations certainly would require some manual sanitization/encryption on the users end. This was not prior since it wasn't something I needed for my use case (I only cared about basic primitives most of the time), but would be nice for other's.

PR looks good to me so far, be sure to lint and add test cases too :)

**Comment by plainerman** [comment]
Great, then I will do the same for the remaining functions, document the changes, and see that the pipeline passes.

One question still: 
I would say, that after write_lock the database should auto_commit (if the variable is set). Do you agree?

**Comment by ex0dus-0x** [comment]
That sounds good! It looks like `auto_commit` doesn't have much of an effect at the moment, so would definitely appreciate adding the functionality there.

**Comment by plainerman** [comment]
Could you look at the changes once more? 
I moved the commit part into the lock function, added doc-tests, and simplified the calls from the namespace class.

From my side, the changes are good to go, since the previous tests also test the new code.

**Comment by ex0dus-0x** [comment]
Thanks @plainerman for your contributions! The refactoring to lock acquisition and passing in a callback all make sense to me, and am also grateful for getting the `auto_commit` functionality to actually operate.

Appreciate all the help with this project!

**Comment by plainerman** [comment]
Thank you very much for merging this so quickly!

**Pull request merged**
