### PR TITLE
support namespace

### PR DESCRIPTION
**Pull request by fewensa**
The namespace can isolate storage.

> In addition, a dependency dirs is added, because `std::env::var("HOME")` does not support windows

### CODE REVIEW

**Comment by fewensa** [comment]
Maybe it is more appropriate to use different storage for different namespaces?

**Comment by fewensa** [comment]
I changed namespace use different storage.  and supports data migration between different versions 
https://github.com/fewensa/microkv/pull/1
Hope to submit pr to you after seeing your comments

**Comment by ex0dus-0x** [comment]
Huge apologies for the long wait on merging this, as other work was prioritized!

Never really thought about the need for namespacing/buckets for the purposes this project was introduced for, but seeing the demand in other projects, will definitely merge to fully support.

Little iffy about introducing another `dirs` dependency, but will introduce for cross-platform compatibility.

**Comment by fewensa** [comment]
In fact, I made a lot of changes after this pr, including the migration after the version upgrade, etc., which became more complicated than before. But I think it can be optimized a bit, and I will submit the pr to you after the modification is completed. If you think it’s okay, I hope it can be merged

**Pull request merged**
